name: Build
on:
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Installing MKDocs
        run: pip install -Iv mkdocs-material==8.2.16
      - name: Installing MKDocs Minify Plugin
        run: pip install mkdocs-minify-plugin
      - name: Building project
        run: mkdocs build
      - name: Uploading Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mkdocs-site
          path: site
