name: Syntax check
on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_call:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing ECLint
        run: npm install -g eclint
      - name: Checking files
        run: eclint check $(git ls-files)