name: Lint Code Base

# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 1

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          LINTER_RULES_PATH: /
          VALIDATE_MARKDOWN: true
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
