name: Publish
on:
  push:
    branches:
      - master
      - main
jobs:
  check:
    name: Check syntax
    uses: ./.github/workflows/check.yml
  build:
    if: github.repository_owner == 'simonyiszk'
    name: Build project
    uses: ./.github/workflows/build.yml
  deploy:
    if: github.repository_owner == 'simonyiszk'
    needs: build
    name: Deploy project
    uses: ./.github/workflows/deploy.yml
